// Browser regression tests with intercepted API responses only. No database access.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const base = process.env.UI_TEST_URL || 'http://127.0.0.1:3000';
const branches = Array.from({ length: 35 }, (_, i) => ({ id: `branch-${i}`, branch_code: `B-${String(i).padStart(2, '0')}`, branch_name: i === 34 ? '=SUM(1,2)' : `Office ${String(i).padStart(2, '0')}`, city: i % 2 ? 'Mumbai' : 'Ahmedabad', email: `office${i}@example.invalid`, is_active: i % 3 !== 0, password_hash: 'NEVER-EXPORT-ME' }));
const projects = branches.map((b, i) => ({ id: `project-${i}`, project_code: `P-${i}`, project_name: `Project ${i}`, client_name: 'Client', branch_name: b.branch_name, project_status: i % 2 ? 'ACTIVE' : 'PLANNING', is_active: true }));
const user = { id: 'user-1', first_name: 'Grid', last_name: 'Reviewer', role_code: 'ROLE_SUPER_ADMIN', primary_branch_id: branches[0].id, permissions: [] };
const task = { id: 'task-1', task_code: 'TASK-1', title: 'Test task', status_id: 's1', task_type_id: 't1', priority: 'HIGH', estimated_hours: 12, assignees: [], created_at: '2026-09-27' };
const checks = [];
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.BROWSER_EXE, headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
    await context.addInitScript(() => localStorage.setItem('ks_access_token', 'grid-fixture'));
    let fail = false;
    let readOnly = false;
    let lastWrite;
    const requests = [];
    await context.route('**/api/v1/**', async route => {
      const req = route.request();
      const url = new URL(req.url());
      const endpoint = url.pathname.replace('/api/v1', '');
      requests.push(`${endpoint}?${url.searchParams}`);
      if (endpoint === '/branches' && fail) return route.fulfill({ status: 500, json: { message: 'Fixture load failed' } });
      if (req.method() !== 'GET') { lastWrite = { endpoint, method: req.method(), body: req.postDataJSON() }; return route.fulfill({ json: { success: true, data: { id: 'new-id' } } }); }
      let data = [];
      let meta = { page: 1, total_pages: 1, total_count: 0 };
      if (endpoint === '/auth/me') data = { user: { ...user, role_code: readOnly ? 'ROLE_VIEWER' : user.role_code }, permissions: [] };
      else if (endpoint === '/branches') data = branches;
      else if (endpoint.startsWith('/branches/')) data = branches.find(b => b.id === endpoint.split('/')[2]);
      else if (endpoint === '/projects') {
        const page = Number(url.searchParams.get('page') || 1);
        data = projects.slice((page - 1) * 20, page * 20);
        meta = { page, total_pages: 2, total_count: 35 };
      }
      else if (/^\/projects\/[^/]+$/.test(endpoint)) data = projects[0];
      else if (endpoint.endsWith('/members')) data = [{ id: 'm1', user_id: 'user-1', full_name: 'Grid Reviewer', project_role: 'Lead', allocation_percentage: 100 }];
      else if (endpoint === '/users') data = { users: [user], totalPages: 1 };
      else if (endpoint === '/tasks') data = { tasks: [task] };
      else if (endpoint === '/tasks/task-1') data = task;
      else if (endpoint === '/tasks/task-1/subtasks') data = [{ id: 'sub-1', title: 'Checklist item', is_completed: false }];
      else if (endpoint === '/task-types') data = [{ id: 't1', type_name: 'Development', type_code: 'DEV' }];
      else if (endpoint === '/task-workflows/statuses') data = [{ id: 's1', status_name: 'Open', status_category: 'TODO' }];
      else if (endpoint.includes('/transitions/')) data = [{ id: 'tr1', from_status_name: 'Open', to_status_name: 'Closed' }];
      else if (endpoint === '/rbac/roles') data = [{ id: 'role-1', role_code: 'DEV', role_name: 'Developer' }];
      else if (endpoint === '/rbac/permissions') data = [{ id: 'perm-1', permission_code: 'TASKS:READ', module: 'TASKS', description: 'Read tasks' }];
      else if (endpoint === '/time-logs') data = { timeLogs: ['12.5', '2', '30'].map((hours, i) => ({ id: `log${i}`, user_id: 'other-user', user_name: `Reviewer ${i}`, task_title: 'Test task', hours_spent: hours, log_date: '2026-09-27', approval_status: 'SUBMITTED', is_billable: true })), totalPages: 1 };
      else if (endpoint === '/audit-logs') data = { auditLogs: [{ id: 'audit1', action_type: 'UPDATE', entity_name: 'tasks', created_at: '2026-09-27', user_name: 'Reviewer' }], totalPages: 1 };
      else if (endpoint === '/notifications') data = { notifications: [{ id: 'n1', title: 'Assigned', body: 'Task assigned', is_read: false, entity_type: 'TASK', entity_id: 'task-1', created_at: '2026-09-27' }], unreadCount: 1, totalPages: 1 };
      else if (endpoint === '/auth/preferences') data = { inApp: true, email: false, push: false };
      else if (endpoint === '/auth/sessions') data = [{ id: 'session1', device_platform: 'WEB', created_at: '2026-09-27', is_current: true }];
      return route.fulfill({ json: { success: true, data, meta } });
    });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('dialog', d => d.accept());
    const ready = async title => {
      const grid = page.getByRole('region', { name: `${title} listing`, exact: true });
      await grid.waitFor();
      await page.waitForFunction(title => document.querySelector(`section[aria-label="${title} listing"]`)?.getAttribute('aria-busy') === 'false', title);
      return grid;
    };
    await page.goto(base + '/admin/branches');
    let grid = await ready('Branches');
    assert.equal(await grid.locator('tbody tr').count(), 10);
    await grid.getByRole('button', { name: 'Next page', exact: true }).click();
    await grid.getByText('Page 2 of 4', { exact: true }).waitFor();
    await grid.getByLabel('Search Branches').fill('Office 34');
    await grid.getByText('No records found', { exact: true }).waitFor();
    await grid.getByLabel('Search Branches').fill('Office 20');
    await grid.getByText('Office 20', { exact: true }).waitFor();
    assert.equal(await grid.locator('tbody tr').count(), 1);
    await grid.getByRole('button', { name: 'Clear search' }).click();
    await grid.getByRole('button', { name: 'Filters', exact: true }).click();
    await grid.getByLabel('Filter City').fill('Mumbai');
    await grid.getByText('17 records', { exact: true }).waitFor();
    await grid.getByRole('button', { name: 'Clear filters', exact: true }).click();
    await grid.getByRole('button', { name: 'Sort', exact: true }).click();
    await grid.getByLabel('Add sort column').selectOption('city');
    await grid.getByLabel('Add sort column').selectOption('branch_code');
    await grid.getByRole('button', { name: 'Toggle Branch Code sort direction' }).click();
    await page.waitForFunction(() => document.querySelector('.listing-table tbody tr td')?.textContent === 'B-34');
    checks.push('Search, empty state, pagination reset, column filters and multi-column sorting');
    await grid.getByRole('button', { name: 'Group', exact: true }).click();
    await grid.getByLabel('Add group column').selectOption('city');
    await grid.getByLabel('Add group column').selectOption('is_active');
    assert.equal(await grid.locator('tbody tr.grid-group-row').count(), 2);
    assert((await grid.locator('tbody tr.grid-group-row').first().innerText()).includes('18 records'));
    await grid.getByRole('button', { name: 'Expand all' }).click();
    await page.waitForFunction(() => document.querySelectorAll('.listing-table tbody tr:not(.grid-group-row)').length === 35);
    checks.push('Nested multi-column grouping and expansion retains all 35 records');
    const downloadPromise = page.waitForEvent('download');
    await grid.getByRole('button', { name: 'Export CSV', exact: true }).click();
    const csv = await fs.readFile(await (await downloadPromise).path(), 'utf8');
    assert.equal(csv.trim().split('\r\n').length, 36);
    assert(csv.includes("'=SUM(1,2)"));
    assert(!csv.includes('NEVER-EXPORT-ME'));
    await page.evaluate(() => {
      const append = Node.prototype.appendChild;
      Node.prototype.appendChild = function(node) {
        const result = append.call(this, node);
        if (node instanceof HTMLIFrameElement) node.contentWindow.print = () => { window.__print = node.contentDocument.body.textContent; };
        return result;
      };
    });
    await grid.getByRole('button', { name: 'Print', exact: true }).click();
    assert((await page.evaluate(() => window.__print)).includes('35 filtered records'));
    await grid.getByLabel('Search Branches').fill('Mumbai');
    await grid.getByText('17 records · 1 groups', { exact: true }).waitFor();
    const filteredDownload = page.waitForEvent('download');
    await grid.getByRole('button', { name: 'Export CSV', exact: true }).click();
    const filteredCsv = await fs.readFile(await (await filteredDownload).path(), 'utf8');
    assert.equal(filteredCsv.trim().split('\r\n').length, 18);
    assert(!filteredCsv.includes('Ahmedabad'));
    await grid.getByRole('button', { name: 'Clear search' }).click();
    checks.push('CSV and print include all filtered records, exclude hidden fields, escape spreadsheet formulas');
    await grid.getByRole('button', { name: 'Clear group' }).click();
    await grid.getByLabel('Search Branches').fill('Office 20');
    await grid.getByRole('button', { name: 'Edit', exact: true }).click();
    await page.getByRole('dialog').waitFor();
    assert.equal(await page.getByRole('dialog').getByLabel('Branch name', { exact: true }).inputValue(), 'Office 20');
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await grid.getByRole('button', { name: 'View', exact: true }).click();
    await page.getByRole('button', { name: 'Close details' }).waitFor();
    await page.getByRole('button', { name: 'Close details' }).click();
    checks.push('View and edit actions preserve existing record forms');
    await page.goto(base + '/projects');
    grid = await ready('Projects');
    await grid.getByText('35 records', { exact: true }).waitFor();
    assert(requests.some(url => url.startsWith('/projects?') && url.includes('page=2')));
    await grid.getByLabel('Search Projects').fill('Project 34');
    await grid.getByText('Project 34', { exact: true }).waitFor();
    await grid.getByRole('button', { name: 'View', exact: true }).click();
    await ready('Team allocation');
    await page.getByRole('button', { name: 'Close details' }).click();
    checks.push('Paginated endpoints load every page before search/sort/group');
    for (const [route, title] of [['/products', 'Products'], ['/versions', 'Versions'], ['/clients', 'Clients'], ['/admin/departments', 'Departments'], ['/admin/designations', 'Designations'], ['/admin/employees', 'Employees'], ['/admin/task-types', 'Task types'], ['/admin/statuses', 'Workflow statuses'], ['/admin/roles', 'Roles'], ['/admin/assignment-rules', 'Assignment rules'], ['/timesheets', 'Timesheets'], ['/audit', 'Audit trail'], ['/notifications', 'Notifications'], ['/releases', 'Release timeline'], ['/profile', 'Device sessions']]) {
      await page.goto(base + route); await ready(title);
    }
    await page.goto(base + '/admin/transitions');
    await page.getByLabel('Task type', { exact: true }).selectOption('t1');
    grid = await ready('Workflow transitions');
    await grid.getByRole('button', { name: 'Delete', exact: true }).click();
    await page.waitForFunction(() => true);
    assert.equal(lastWrite?.method, 'DELETE');
    assert.equal(lastWrite?.endpoint, '/task-workflows/transitions/tr1');
    await page.goto(base + '/admin/permissions');
    await page.getByLabel('Permission subject').selectOption('role-1');
    grid = await ready('Permissions');
    await grid.getByLabel('TASKS:READ', { exact: true }).selectOption('grant');
    await page.goto(base + '/tasks');
    await page.getByRole('button', { name: 'Table', exact: true }).click();
    grid = await ready('Tasks');
    await grid.getByText('Test task', { exact: true }).waitFor();
    await grid.getByRole('button', { name: 'Edit', exact: true }).click();
    await page.getByLabel('Title', { exact: false }).waitFor();
    assert.equal(await page.getByLabel('Title', { exact: false }).inputValue(), 'Test task');
    await page.goto(base + '/tasks');
    await page.getByRole('button', { name: 'Table', exact: true }).click();
    grid = await ready('Tasks');
    await grid.getByRole('button', { name: 'View', exact: true }).click();
    await page.getByRole('button', { name: /Subtasks/, exact: false }).click();
    await ready('Subtasks');
    await page.goto(base + '/timesheets');
    grid = await ready('Timesheets');
    await grid.getByRole('button', { name: 'Sort', exact: true }).click();
    await grid.getByLabel('Add sort column').selectOption('hours_spent');
    await page.waitForFunction(() => document.querySelector('.listing-table tbody tr td:nth-child(5)')?.textContent === '2');
    checks.push('Related-record/subtask lists and direct task editing work; numeric columns sort numerically');
    checks.push('All routed listings share the grid; workflow delete and permission editing remain available');
    readOnly = true;
    await page.goto(base + '/admin/branches');
    grid = await ready('Branches');
    assert.equal(await grid.getByRole('button', { name: 'Add Branch', exact: true }).count(), 0);
    assert.equal(await grid.getByRole('button', { name: 'Edit', exact: true }).count(), 0);
    checks.push('Read-only user has no unauthorized master write actions');
    readOnly = false;
    fail = true;
    await page.goto(base + '/admin/branches'); grid = await ready('Branches');
    await grid.getByRole('alert').waitFor();
    assert(await grid.getByRole('button', { name: 'Export CSV' }).isDisabled());
    fail = false;
    await grid.getByRole('button', { name: 'Retry' }).click();
    await grid.getByText('35 records', { exact: true }).waitFor();
    checks.push('Fetch errors hide incomplete results, disable export, and allow retry');
    for (const theme of ['light', 'dark']) {
      await page.evaluate(theme => localStorage.setItem('ks_theme', theme), theme);
      await page.reload(); grid = await ready('Branches');
      const bg = await grid.evaluate(el => getComputedStyle(el).backgroundColor);
      assert(theme === 'dark' ? Number(bg.match(/\d+/)[0]) < 80 : Number(bg.match(/\d+/)[0]) > 200);
      await page.screenshot({ path: path.resolve(__dirname, `../../docs/walkthrough/data-grid-${theme}.png`), fullPage: true });
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(400);
    await page.screenshot({ path: path.resolve(__dirname, '../../docs/walkthrough/data-grid-mobile.png'), fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    checks.push('Light/dark colors and mobile layout without page overflow');
    assert.deepEqual(errors, []);
    console.log(JSON.stringify(checks, null, 2));
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
