const fs = require('fs'); const path = require('path'); const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../../docs/walkthrough');
const dataset = JSON.parse(fs.readFileSync(path.join(root, 'requirements-browser-results.json'))).find(r => r.check === 'Created test dataset');
const results = []; let token; let employeeToken;
async function api(url, method = 'GET', body, expected = 200, bearer = token) {
  const r = await fetch(`http://localhost:5000/api/v1${url}`, { method, headers: { 'Content-Type': 'application/json', ...(bearer ? { Authorization: `Bearer ${bearer}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
  const json = await r.json(); assert.equal(r.status, expected, `${method} ${url}: ${JSON.stringify(json.message)}`); return json.data;
}
async function check(name, fn) { try { await fn(); results.push({ check: name, status: 'passed' }); } catch (e) { results.push({ check: name, status: 'failed', message: e.message }); process.exitCode = 1; } }
async function main() {
  const login = await api('/auth/login-password', 'POST', { email: process.env.TEST_EMAIL, password: process.env.TEST_PASSWORD }); token = login.accessToken;
  const employee = await api(`/users/${dataset.employee}`);
  employeeToken = (await api('/auth/login-password', 'POST', { email: employee.email, password: 'QaTestOnly@2026' })).accessToken;
  await check('Employee emergency contact and employment status persist', async () => { await api(`/users/${dataset.employee}`, 'PUT', { emergencyContact: 'QA emergency +919000000001', employmentStatus: 'ACTIVE' }); const e = await api(`/users/${dataset.employee}`); assert.equal(e.emergency_contact, 'QA emergency +919000000001'); assert.equal(e.employment_status, 'ACTIVE'); });
  await check('Product technical, documentation and commercial fields persist', async () => { await api(`/products/${dataset.product}`, 'PUT', { techStack: 'TypeScript / PostgreSQL', documentationLinks: 'https://example.invalid/qa-docs', subscriptionPlans: 'QA annual plan', implementationFee: 500 }); const p = await api(`/products/${dataset.product}`); assert.equal(p.tech_stack, 'TypeScript / PostgreSQL'); assert.equal(Number(p.implementation_fee), 500); assert.equal(p.subscription_plans, 'QA annual plan'); });
  await check('Project technical, invoice and actual-date fields persist', async () => { await api(`/projects/${dataset.project}`, 'PUT', { techStack: 'React / NestJS', invoicingMilestones: 'QA milestone: 50% on delivery', actualStartDate: '2026-09-25' }); const p = await api(`/projects/${dataset.project}`); assert.equal(p.tech_stack, 'React / NestJS'); assert.match(p.invoicing_milestones, /50%/); });
  await check('Task severity and actual dates persist', async () => { await api(`/tasks/${dataset.task}`, 'PUT', { severity: 'MAJOR', actualStartDate: '2026-09-25' }); assert.equal((await api(`/tasks/${dataset.task}`)).severity, 'MAJOR'); });
  await check('Task type default severity and custom field schema persist', async () => { await api(`/task-types/${dataset.type}`, 'PUT', { defaultSeverity: 'MINOR', customFields: { browser: { type: 'text', required: false } } }); const t = await api(`/task-types/${dataset.type}`); assert.equal(t.default_severity, 'MINOR'); assert.equal(t.custom_fields.browser.type, 'text'); });
  await check('New tasks inherit task-type severity and billing defaults', async () => { await api(`/task-types/${dataset.type}`, 'PUT', { defaultSeverity: 'MINOR', isChargeableDefault: true }); const task = await api('/tasks', 'POST', { title: `${dataset.stamp} Type defaults`, taskTypeId: dataset.type, projectId: dataset.project, branchId: dataset.branch }, 201); assert.equal(task.severity, 'MINOR'); assert.equal(task.is_chargeable, true); });
  await check('Employee activation keeps employment status consistent', async () => { await api(`/users/${dataset.employee}/status`, 'PATCH', { isActive: false }); assert.equal((await api(`/users/${dataset.employee}`)).employment_status, 'INACTIVE'); await api(`/users/${dataset.employee}/status`, 'PATCH', { isActive: true }); assert.equal((await api(`/users/${dataset.employee}`)).employment_status, 'ACTIVE'); });
  await check('Client license support tier persists', async () => { const mappings = await api(`/products/${dataset.product}/clients`); assert(mappings.length); await api(`/products/clients/${mappings[0].id}`, 'PUT', { supportTier: 'QA Tier 2' }); const after = await api(`/products/${dataset.product}/clients`); assert.equal(after[0].support_tier, 'QA Tier 2'); });
  await check('Subtask list query and completion', async () => { const child = await api(`/tasks/${dataset.task}/subtasks`, 'POST', { title: `${dataset.stamp} Verified subtask` }, 201); await api(`/tasks/subtasks/${child.id}/toggle`, 'PATCH', { isCompleted: true }); const rows = await api(`/tasks/${dataset.task}/subtasks`); assert(rows.some(r => r.id === child.id && r.is_completed)); });
  await check('Timesheet submit, reject, resubmit and approve', async () => {
    const permissions = await api('/rbac/permissions'); const own = permissions.find(p => p.permission_code === 'TIMELOGS:LOG_OWN'); await api(`/rbac/roles/${dataset.role}/permissions/${own.id}`, 'PUT', { effect: 'grant' });
    const log = await api('/time-logs', 'POST', { taskId: dataset.task, logDate: '2026-09-25', hoursSpent: 0.5, description: `${dataset.stamp} Approval test`, isOvertime: true, isWeekend: false, isBillable: false }, 201, employeeToken);
    assert.equal(log.is_overtime, true); await api(`/time-logs/${log.id}/submit`, 'PATCH', {}, 200, employeeToken);
    await api(`/time-logs/${log.id}/review`, 'PATCH', { status: 'REJECTED', remarks: 'QA rejection check' });
    await api(`/time-logs/${log.id}/submit`, 'PATCH', {}, 200, employeeToken);
    await api(`/time-logs/${log.id}/review`, 'PATCH', { status: 'APPROVED', remarks: 'QA approved' });
    const logs = await api(`/time-logs?taskId=${dataset.task}`); assert.equal(logs.timeLogs.find(l => l.id === log.id).approval_status, 'APPROVED');
    await api(`/time-logs/${log.id}`, 'DELETE', undefined, 403, employeeToken);
  });
  await check('Notification preferences persist for test employee', async () => { await api('/auth/preferences', 'PUT', { inApp: true, email: false, push: false }, 200, employeeToken); const p = await api('/auth/preferences', 'GET', undefined, 200, employeeToken); assert.equal(p.email, false); });
  await check('In-app task event notification delivered', async () => { await api(`/tasks/${dataset.task}/assignees`, 'PUT', { assigneeIds: [dataset.employee], primaryAssigneeId: dataset.employee }); const n = await api('/notifications', 'GET', undefined, 200, employeeToken); assert(n.notifications.some(n => n.entity_id === dataset.task)); });
  await check('Refresh rotation rejects replay', async () => { const auth = await api('/auth/login-password', 'POST', { email: employee.email, password: 'QaTestOnly@2026' }); const renewed = await api('/auth/refresh-token', 'POST', { refreshToken: auth.refreshToken }); assert(renewed.refreshToken !== auth.refreshToken); await api('/auth/refresh-token', 'POST', { refreshToken: auth.refreshToken }, 401); await api('/auth/me', 'GET', undefined, 200, renewed.accessToken); });
  await check('Remote session revocation rejects access and refresh', async () => { const auth = await api('/auth/login-password', 'POST', { email: employee.email, password: 'QaTestOnly@2026' }); const sessions = await api('/auth/sessions', 'GET', undefined, 200, auth.accessToken); const current = sessions.find(s => s.is_current); assert(current); await api(`/auth/sessions/${current.id}`, 'DELETE', undefined, 200, employeeToken); await api('/auth/me', 'GET', undefined, 401, auth.accessToken); await api('/auth/refresh-token', 'POST', { refreshToken: auth.refreshToken }, 401); });
  await check('Server rejects inverted project dates', async () => { await api(`/projects/${dataset.project}`, 'PUT', { plannedEndDate: '2026-01-01' }, 400); });
  fs.writeFileSync(path.join(root, 'requirements-schema-results.json'), JSON.stringify(results, null, 2)); console.log(JSON.stringify(results, null, 2));
}
main().catch(e => { console.error(e.message); process.exitCode = 1; });
